name: Test Computor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Computor
      run: |
        make

    - name: Run Computor
      run: |
        ./computor "-6 * X^0 - 1 * X^1 + 1 * X^2 = 0"
      run: |
        ./computor  "-6 * X^0 - 1 * X^1 + 1 * X^2 + 1 * X^3= 0"
